#!perl

# DATE
# VERSION

use strict;
use warnings;
use App::perlmv;

my $pmv = App::perlmv->new;
$pmv->{ 'mode' } = 'rename';
$pmv->run;

1;
# ABSTRACT: Rename files using Perl code
# PODNAME:

=head1 DESCRIPTION

See L<perlmv> for more documentation.

=head1 SEE ALSO

L<perlmv>

=cut
