#!perl

# DATE
# VERSION

use strict;
use warnings;
use App::perlmv;
use Getopt::Long::Complete; # just so we can detect script as using Getopt::Long::Complete

my $pmv = App::perlmv->new;
$pmv->{ 'mode' } = 'copy';
$pmv->run;

1;
# ABSTRACT: Copy files using Perl code
# PODNAME:

=head1 DESCRIPTION

See L<perlmv> for more documentation.

=head1 SEE ALSO

L<perlmv>

=cut
